services:
  todominimalapi:
    image: ${DOCKER_REGISTRY-}todominimalapi
    build:
      context: .
      dockerfile: TodoMinimalApi/Dockerfile
    environment:
        - ASPNETCORE_URLS=http://+:8080
        - ConnectionStrings__Postgres=Host=postgres;Database=todos;Username=postgres;Password=postgres
    ports:
        - "8080:8080"
    depends_on:
        - postgres

  postgres:
    image: postgres:latest
    container_name: todo_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todos
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: